name: saudeapp
description: "A new Flutter project."
publish_to: 'none'

version: 2.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  supabase_flutter: ^2.12.0
  geolocator: ^14.0.2
  latlong2: ^0.9.1
  flutter_map: ^8.2.2
  shared_preferences: ^2.3.5
  flutter_local_notifications: ^17.2.3
  timezone: ^0.9.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.3.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.png

# Configuração do Splash Screen
flutter_native_splash:
  color: "#FFFFFF"
  image: assets/images/logo.png
  android: true
  ios: false